cmake: Allow external control of whether to test or install
KhronosGroup/Vulkan-Headers pull request #471
Opened 2024-02-13 19:29 UTC by dneto0

This makes the project more composable: It can be built and tested as part of a larger set of projects, from source.

2024-02-13 19:38 UTC, charles-lunarg requested changes
Because this changes the name of BUILD_TESTS, it breaks anyone's local build but also breaks the github actions CI job. 

https://github.com/KhronosGroup/Vulkan-Headers/blob/5ac36269f50381bdd92a5e1973d8eb041771e59e/.github/workflows/ci.yml#L32

While I'm not sure there is a policy around the naming, the `BUILD_TESTS` was consistent across other Vulkan repositories. Having a per-repo variable allows tighter control of which repo's are doing what when vendored, but it is not common for vendored repo's to want to test their dependencies. 

Put another way, if you want to change the variable name, at least change all occurrences of it in the codebase.

2024-06-14 20:28 UTC, juan-kitware commented on CMakeLists.txt
> +	message("enabling install")
By default this will be directed to stderr. I'd just remove the message. Or change the mode to DEBUG instead.

2024-06-14 20:30 UTC, juan-kitware commented on CMakeLists.txt
> +	include(GNUInstallDirs)
indentation issue

2024-06-14 20:38 UTC, charles-lunarg approved these changes
I went ahead and applied the name change into ci.yml. VULKAN_HEADERS_ENABLE_TESTS is a mouthful but it is very explicit and wont be enabled by accident.

2024-06-14 20:39 UTC, juan-kitware approved these changes
I'd rebase and squash to make this into 1 commit. Other than that LGTM

2024-06-14 20:42 UTC, merged